import type { Metadata } from "next";

import { themeFontClassName } from "@/lib/theme";
import { cn } from "@/lib/utils";
import { ErrorReporterProvider } from "@major-tech/error-reporter/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create major Build App",
  description: "Generated by major Build",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // RootLayout is a server component, so it can read the (server-only) app id
  // env vars and pass the value down as a prop — the browser can't read them
  // itself. Without this, the client reporter has no applicationId and drops
  // browser/React errors.
  const majorApplicationId =
    process.env.APPLICATION_ID || process.env.MAJOR_APPLICATION_ID || "";

  return (
    <html lang="en">
      <body className={cn(themeFontClassName, "antialiased")}>
        <ErrorReporterProvider
          endpoint={process.env.MAJOR_API_BASE_URL || ""}
          jwtToken={process.env.MAJOR_JWT_TOKEN || ""}
          applicationId={majorApplicationId}
        >
          {children}
        </ErrorReporterProvider>
      </body>
    </html>
  );
}
