import type { Metadata } from "next";

import { themeFontClassName } from "@/lib/theme";
import { cn } from "@/lib/utils";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create major Build App",
  description: "Generated by major Build",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(themeFontClassName, "antialiased")}>
        {children}
      </body>
    </html>
  );
}
